#baseurl:/rolinawu.github.io 

#baseurl:"rolinawu.github.io"

# Site live URL
url: http://rolinawu.github.io/blog

# Localhost 
#url: http://127.0.0.1:4000  

excerpt_separator: "d596aa409dbcf4bf9d9d57252304a921bd02e3fc"

harmony:
  name: Comic Learning
  description: Comics + Machine Learning = Awesomeness

  meta_description: #> #
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Rolina Wu
    email: 
    url: http://www.rolinawu.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key: #UA-xxxx-x

  # Profile links, leave blank to ignore
social:
  github: ''
  linkedin: ''
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
